sidebar:
  menu:
    post: '[btn.blog](/)'
    wiki: '[btn.wiki](/wiki/)'
    notes: '[ç¬”è®°](/notes/)'
    more: '[æ›´å¤š](/more/)'
    friends: '[å‹é“¾](/links/)'
  widgets:
    home: search, welcome, toc, timeline, ghuser
    
comments:
  service: giscus
  # giscus
  # https://giscus.app/zh-CN
  giscus:
    data-repo: Xi-Meng-001/blog-comments # [åœ¨æ­¤è¾“å…¥ä»“åº“]
    data-repo-id: R_kgDOKMuhPw # [åœ¨æ­¤è¾“å…¥ä»“åº“ ID]
    data-category: General # [åœ¨æ­¤è¾“å…¥åˆ†ç±»å]
    data-category-id: DIC_kwDOKMuhP84CY78Y
    data-mapping: pathname
    data-strict: 0
    data-reactions-enabled: 1
    data-emit-metadata: 0
    data-input-position: top # top, bottom
    data-theme: preferred_color_scheme
    data-lang: zh-CN
    data-loading: lazy
    crossorigin: anonymous

article:
  # npm i hexo-related-popular-posts
  related_posts:
    enable: true
    title: æ‚¨å¯èƒ½æ„Ÿå…´è¶£çš„æ–‡ç« 

tag_plugins:
  emoji:
    2233: https://github.com/Xi-Meng-001/2233Emoji/blob/main/${name}.png

footer:
  social:
    github:
      icon: '<img src="https://gcore.jsdelivr.net/gh/cdn-x/placeholder@1.0.4/social/08a41b181ce68.svg"/>'
      url: https://github.com/Xi-Meng-001
  sitemap:
     'åšå®¢':
       - '[ğŸ“ è¿‘æœŸå‘å¸ƒ](/)'
       - '[ğŸ“ å†å²æ–‡ç« ](/archives)'
       - '[ğŸ·ï¸ æ ‡ç­¾](/tags)'
       - '[ğŸ“ƒ æ–‡æ¡£](/wiki)'
       - '[ğŸ”— å‹æƒ…é“¾æ¥](/links)'
     'ç¤¾äº¤':
       - '[ğŸ± GitHub](https://github.com/Xi-Meng-001)'
       - '[ğŸ§ QQ](https://qm.qq.com/q/Jcadj7ExQm)'
       - '[ğŸ“º Bç«™](https://b23.tv/TFEJ7Z7)'
  content: | # æ”¯æŒ Markdown æ ¼å¼
    æœ¬ç«™ç”± [@éˆ´æœ¨èŠ±è¯](/) ä½¿ç”¨ [Stellar](https://github.com/xaoxuu/hexo-theme-stellar) ä¸»é¢˜åˆ›å»ºã€‚
    æœ¬åšå®¢æ‰€æœ‰æ–‡ç« é™¤ç‰¹åˆ«å£°æ˜å¤–ï¼Œå‡é‡‡ç”¨ [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) è®¸å¯åè®®ï¼Œè½¬è½½è¯·æ³¨æ˜å‡ºå¤„ã€‚
                   [â›© èŒICPå¤‡20230142å·](https://icp.gov.moe/?keyword=20230142)
