logo:
  avatar: '[config.avatar](/about/)' # you can set avatar link in _config.yml or '[https://xxx.png](/about/)'
  title: '[config.title](/)' # you can set html tag like: '[<img no-lazy height="32px" src="xxx"/>](/)'
  subtitle: 'åœ°çƒé‡Œçš„ä¸çŸ¥åå­˜åœ¨_(:3ã€âˆ )_'
menubar:
  columns: 4
  items:
     - id: post
       title: åšå®¢
       url: /
     - id: friends
       title: å‹é“¾
       url: /links/
     - id: bangumis
       title: è¿½ç•ª
       url: /bangumis/
     - id: more
       title: æ›´å¤š
       url: /more/
     
    
site_tree:
  # ä¸»é¡µé…ç½®
  home:
    sidebar: search, welcome, toc

comments:
  service: giscus
  # giscus
  # https://giscus.app/zh-CN
  giscus:
    data-repo: Suzukif-2048/blog-comments # [åœ¨æ­¤è¾“å…¥ä»“åº“]
    data-repo-id: R_kgDOKMuhPw # [åœ¨æ­¤è¾“å…¥ä»“åº“ ID]
    data-category: General # [åœ¨æ­¤è¾“å…¥åˆ†ç±»å]
    data-category-id: DIC_kwDOKMuhP84CY78Y
    data-mapping: pathname
    data-strict: 0
    data-reactions-enabled: 1
    data-emit-metadata: 0
    data-input-position: top # top, bottom
    data-theme: preferred_color_scheme
    data-lang: zh-CN
    data-loading: lazy
    crossorigin: anonymous

article:
  share: [wechat, weibo, email, link]
  # npm i hexo-related-popular-posts
  related_posts:
    enable: true
    title: æ‚¨å¯èƒ½æ„Ÿå…´è¶£çš„æ–‡ç« 

style:
  sidebar:
    blur: true

tag_plugins:
  emoji:
    bilibili: https://gcore.jsdelivr.net/gh/Suzukif-2048/BlogFile/image/${name}.png
  quot:
    default:
      prefix: https://bu.dusays.com/2022/10/24/63567d3e092ff.png
      suffix: https://bu.dusays.com/2022/10/24/63567d3e0ab55.png
    hashtag:
      prefix: https://bu.dusays.com/2022/10/24/63567d3e07da3.png
    mcskins:
      prefix: https://s.namemc.com/2d/skin/face.png?id=27a2cd334ded7f4a&scale=4
    gear:
      prefix: https://s2.loli.net/2023/11/13/kdLo13HPeWiDJhv.png
    love:
      prefix: https://s2.loli.net/2023/11/18/oKxaEMQ2icBAGzw.png
    timeline:
      prefix: https://gcore.jsdelivr.net/gh/Suzukif-2048/BlogFile@main/svg/%E5%8A%A8%E6%80%81.svg
footer:
  social:
    github:
      icon: '<img src="https://gcore.jsdelivr.net/gh/cdn-x/placeholder@1.0.4/social/08a41b181ce68.svg"/>'
      url: https://github.com/Suzukif-2048
    bilibili:
      icon: '<img src="https://gcore.jsdelivr.net/gh/Suzukif-2048/BlogFile@master/svg/bilibili.svg">'
      url: https://b23.tv/PthDTzg
    qq:
      icon: '<img src="https://gcore.jsdelivr.net/gh/Suzukif-2048/BlogFile@master/svg/QQ.svg">'
      url: https://qm.qq.com/q/hDdPUKaNiM
  sitemap:
     'åšå®¢':
       - '[ğŸ“ è¿‘æœŸå‘å¸ƒ](/)'
       - '[ğŸ“ å†å²æ–‡ç« ](/archives)'
       - '[ğŸ·ï¸ æ ‡ç­¾](/tags)'
       - '[ğŸ“ƒ æ–‡æ¡£](/wiki)'
       - '[ğŸ”— å‹æƒ…é“¾æ¥](/links)'
     'ç½‘ç«™':
       - '[ğŸ  ä¸ªäººä¸»é¡µ](https://home.suzukif.xyz/)'
       - '[ğŸ“ Alist](https://file.suzukif.xyz/)'
     'ç¤¾äº¤':
       - '[ğŸ± GitHub](https://github.com/Suzukif-2048)'
       - '[ğŸ§ QQ](https://qm.qq.com/q/Jcadj7ExQm)'
       - '[ğŸ“º Bç«™](https://b23.tv/TFEJ7Z7)'
  content: | # æ”¯æŒ Markdown æ ¼å¼
    æœ¬ç«™ç”± [${author.name}](/) ä½¿ç”¨ [${theme.name} ${theme.version}](${theme.tree}) ä¸»é¢˜åˆ›å»ºã€‚
    æœ¬åšå®¢æ‰€æœ‰æ–‡ç« é™¤ç‰¹åˆ«å£°æ˜å¤–ï¼Œå‡é‡‡ç”¨ [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) è®¸å¯åè®®ï¼Œè½¬è½½è¯·æ³¨æ˜å‡ºå¤„ã€‚
    [â›© èŒICPå¤‡20230142å·](https://icp.gov.moe/?keyword=20230142)
