sidebar:
  menu:
    post: '[btn.blog](/)'
    wiki: '[btn.wiki](/wiki/)'
    notes: '[ç¬”è®°](/notes/)'
    more: '[æ›´å¤š](/more/)'
    friends: '[å‹é“¾](/links/)'
  widgets:
    home: search, welcome, toc, timeline, ghuser
    
comments:
  service: waline
  waline:
    js: https://unpkg.com/@waline/client@v2/dist/waline.js
    css: https://unpkg.com/@waline/client@v2/dist/waline.css
    # Waline server address url, you should set this to your own link
    serverURL: https://1jwow8usidowkqqj.isese.top/ # waline åœ°å€
    # If false, comment count will only be displayed in post page, not in home page
    commentCount: true
    # Pageviews count, Note: You should not enable both `waline.pageview` and `leancloud_visitors`.
    pageview: false

    # Custom locales
    locale:
      placeholder: # è¾“å…¥æ¡†å†…æç¤ºæ–‡å­—

    # Custom emoji
    emoji: 
      - https://gcore.jsdelivr.net/gh/norevi/waline-blobcatemojis@1.0/blobs
    #   - https://unpkg.com/@waline/emojis@1.1.0/weibo
    #   - https://unpkg.com/@waline/emojis@1.1.0/alus
    #   - https://unpkg.com/@waline/emojis@1.1.0/bilibili
    #   - https://unpkg.com/@waline/emojis@1.1.0/qq
    #   - https://unpkg.com/@waline/emojis@1.1.0/tieba
    #   - https://unpkg.com/@waline/emojis@1.1.0/tw-emoji
    #   - https://unpkg.com/@waline/emojis@1.1.0/bmoji

article:
  # npm i hexo-related-popular-posts
  related_posts:
    enable: true
    title: æ‚¨å¯èƒ½æ„Ÿå…´è¶£çš„æ–‡ç« 

footer:
  social:
    github:
      icon: '<img src="https://gcore.jsdelivr.net/gh/cdn-x/placeholder@1.0.4/social/08a41b181ce68.svg"/>'
      url: https://github.com/Xi-Meng-001
  sitemap:
     'æˆ‘çš„åšå®¢ï¼ˆï¿£â–½ï¿£ï¼‰':
       - '[ğŸ“ è¿‘æœŸå‘å¸ƒ](/)'
       - '[ğŸ“ å†å²æ–‡ç« ](/archives)'
       - '[ğŸ·ï¸ æ ‡ç­¾](/tags)'
       - '[ğŸ“ƒ æ–‡æ¡£](/wiki)'
       - '[ğŸ”— å‹æƒ…é“¾æ¥](/links)'
     'ä¸»äººçš„ç½‘ç«™ãƒ¾ï¾‰â‰§âˆ€â‰¦)o':
       - '[ğŸ—¨ï¸ è®ºå›](https://bbs.isese.top/)'
       - '[ğŸ—’ Wiki](https://wiki.isese.top/)'
     'ä¸»äººçš„ç¤¾äº¤è´¦å·ãƒ¾(â€â—â—¡â—)ï¾‰':
       - '[ğŸ± GitHub](https://github.com/Xi-Meng-001)'
       - '[ğŸ§ QQ](https://qm.qq.com/q/Jcadj7ExQm)'
  content: | # æ”¯æŒ Markdown æ ¼å¼
    æœ¬ç«™ç”± [@éˆ´æœ¨èŠ±è¯](/) ä½¿ç”¨ [Stellar](https://github.com/xaoxuu/hexo-theme-stellar) ä¸»é¢˜åˆ›å»ºã€‚
    æœ¬åšå®¢æ‰€æœ‰æ–‡ç« é™¤ç‰¹åˆ«å£°æ˜å¤–ï¼Œå‡é‡‡ç”¨ [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) è®¸å¯åè®®ï¼Œè½¬è½½è¯·æ³¨æ˜å‡ºå¤„ã€‚
                   [â›© èŒICPå¤‡20230142å·](https://icp.gov.moe/?keyword=20230142)